### ISSUE TITLE
博主有联系方式吗？想谈合作~

### ISSUE THREAD

**Issue by sssssshift** [sb-child/sea#1]

**Comment by sb-child** [comment]
@sssssshift ~~草？~~ 请细说呢

**Comment by sssssshift** [comment]
就是海外IP代理 这上面不好详细发 方便您可以加我微信：18020104227

**Comment by sb-child** [comment]
spambot? closed

**Comment by sssssshift** [comment]
真人活人 不是机器人

**Comment by sb-child** [comment]
> 真人活人 不是机器人

![图片](https://user-images.githubusercontent.com/55868015/228491880-8dcb7296-0db8-4e1c-9d0d-c9f3eba86181.png)

i think you are a spambot

**Comment by sssssshift** [comment]
hhhhhhh懒得换话术 累了
